### ISSUE TITLE
🐞 [Bug]: Direct Messages appear in iOS notifications, not visible in messages window

### ISSUE THREAD

**Issue by JFRHorton** [meshtastic/Meshtastic-Apple#1075]
### Firmware Version

2.5.17

### What did you do?

iPhone 13, iOS 18.1.1, Meshtastic iOS app version 2.5.17

Connected to node in client mode, received/sent messages to another client node within range (same room) both via direct message and over a channel.

### Expected Behavior

Expect to see “chat” style message display in direct message window for node

### Current Behavior

When receiving a direct message, a notification is visible on the iOS notifications page, and the count of direct messages increases. However, when opening the direct messages page, none are visible.
Transmitting a direct message works as expected, except the transmitted message is not visible in the chat window.

Channel messaging behaves as expected.

![Image](https://github.com/user-attachments/assets/d984c744-0e28-4b60-91ce-eeb8cca8207b)

![Image](https://github.com/user-attachments/assets/fa97e9ec-6e74-4e9b-af1c-b8616e6fbd83)

![Image](https://github.com/user-attachments/assets/b54b02ef-366f-48f4-b830-67b3bd84a628)

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by dylanbox** [comment]
Also encountering this

**Comment by RCGV1** [comment]
@rcarteraz The user stated that the nodes are in the same room so probably not over MQTT.

**Comment by AA7US** [comment]
I'm also experiencing this bug with latest iOS app and node firmware. It's happening when receiving DM's directly via RF (no MQTT is involved as mentioned in issue #1051).

**Comment by vpnels** [comment]
Also seeing this. Where are the DMs? I can't find them. Clicking the notice takes me to the Contacts page. No DMs.

**Comment by morria** [comment]
I frequently see this issue as well. It appeared to occur when I receive a DM message from someone before receiving their NodeInfo or User info.

If I'm reading this right, it looks like the `messageList` is populated by [this query](https://github.com/meshtastic/Meshtastic-Apple/blob/36d6664dfcff799e798970020423f02ebea03d93/Meshtastic/Extensions/CoreData/UserEntityExtension.swift#L18) which filters on

```swift
NSPredicate(format: "((toUser == %@) OR (fromUser == %@)) AND toUser != nil AND fromUser != nil AND isEmoji == false AND admin = false AND portNum != 10", self, self)
```

with `self` serializing with all available user info including `shortName` and `longName` as seen when adding a log line there as `NSLog("UserEntity: %@", self)`.

Should messages be keyed off of `nodeId` instead since we can only be guaranteed to have that nodeId for messages that appear before `NodeInfo`?

If we'd get away with that we could just change what we key messages on at insert and lookup time, or add a `description` value to the `UserInfo` extension that only includes the `id`.


```swift
       public override var description: String {
               return "User(id: \(id)"
       }
```

**Comment by garthvh** [comment]
> I frequently see this issue as well. It appeared to occur when I receive a DM message from someone before receiving their NodeInfo or User info.
> 
> If I'm reading this right, it looks like the `messageList` is populated by [this query](https://github.com/meshtastic/Meshtastic-Apple/blob/36d6664dfcff799e798970020423f02ebea03d93/Meshtastic/Extensions/CoreData/UserEntityExtension.swift#L18) which filters on
> 
> NSPredicate(format: "((toUser == %@) OR (fromUser == %@)) AND toUser != nil AND fromUser != nil AND isEmoji == false AND admin = false AND portNum != 10", self, self)
> with `self` serializing with all available user info including `shortName` and `longName` as seen when adding a log line there as `NSLog("UserEntity: %@", self)`.
> 
> Should messages be keyed off of `nodeId` instead since we can only be guaranteed to have that nodeId for messages that appear before `NodeInfo`?
> 
> If we'd get away with that we could just change what we key messages on at insert and lookup time, or add a `description` value to the `UserInfo` extension that only includes the `id`.
> 
>        public override var description: String {
>                return "User(id: \(id)"
>        }

A node info and user is created from the nodeid automatically every time a packet is received from a node that is not in the node list.

**Comment by garthvh** [comment]
Can't replicate this issue.

**Comment by xe1brx** [comment]
I have the same problem.  LORA, no MTTQ.

**Comment by GregIthaca** [comment]
We have six people sharing an MQTT server. There are no problems with the Android devices. There are no problems with public messages.
However, for all of us on iPhone, we see notifications for all incoming messages, but only **some** of the private messages are reflected in devices under the contacts. The other Direct Messages show completely blank screens. They do not even reflect the **outgoing** messages that are sent to that user, which seems like it might be helpful/indicative.
I have some screen shots I can share if that helps.

**Comment by RCGV1** [comment]
Is this via MQTT? There's been some issues with sending dms via mqtt I think unrelated to this issue.

**Comment by bconway** [comment]
> Is this via MQTT? There's been some issues with sending dms via mqtt I think unrelated to this issue.

In my case, no. MQTT is disabled everywhere.

**Comment by GregIthaca** [comment]
I don't have a big enough local group to test it not over MQTT, so I can't say for sure if the issue appears for DMs in general. But it was very informative that we had both Android and Apple users on the call and could see how the problem was not replicable on Android.

**Comment by RCGV1** [comment]
I heard someone mentioned that this happens when that node cycles out of your node db and when they send you a message it doesn't end up in messages screen. We need to narrow this issue down so that we can fix it, any logs (device or from iOS), screenshots, and screen recordings would be appreciated.

**Comment by garthvh** [comment]
I think this was fixed in 2.6.1

**Comment by GregIthaca** [comment]
I'm running 2.6.1, and another person who was seeing the same thing. I'm not sure how to get what logs you are looking for, but if you tell me where to look I'm happy to try to reproduce. In the meantime here is a screenshot of a message notification, and the (blank) message history behind it as soon as the notification went off-screen. You can also the red (5) notification bubble, but there is no way to clear it by looking at the (non-existent) messages.

![Image](https://github.com/user-attachments/assets/0a29250f-3b7e-43af-a255-557d88158461)

![Image](https://github.com/user-attachments/assets/9b98eff9-0e53-48f4-8735-bc6e1534021b)

**Comment by bconway** [comment]
Still seeing this on iOS app 2.6.2. Notification comes in, the message list shows no new items in the list, and clicking on the notification takes me to an empty public channel. Screenshots attached.

![Image](https://github.com/user-attachments/assets/e93819c2-7711-41dd-beb8-bbf563f1b690)
![Image](https://github.com/user-attachments/assets/ce88ef8b-3850-4637-8bb9-0a31a074e20f)
![Image](https://github.com/user-attachments/assets/a029ec7c-50a4-4a60-89c5-2ca9d4d9418b)

**Comment by bconway** [comment]
I've been able to gather some more data, as this is a continued problem on the latest iOS release. I have two nodes set up near each other with similar capabilities, one using the web client via wifi, and one using iOS via bluetooth. Both nodes are configured identically, other than the Heltec on wifi. From a segment of today:

Web client: 3 messages
iOS notifications: 3 messages (the same ones)
iOS chat: 2 messages (2 expected, one missing).

So it appears that the issue is not with the iOS-connected node, nor the messages being received by iOS. Can this be reopened? Thanks.

<img width="498" height="364" alt="Image" src="https://github.com/user-attachments/assets/e9fd035a-9d3c-4b7f-8b10-c058adf9c489" />

![Image](https://github.com/user-attachments/assets/7e7cb4e7-2790-44c8-a41f-117822343cfa)

![Image](https://github.com/user-attachments/assets/6725bd53-2096-4557-9b1d-e611ca9b49d7)

**Comment by RCGV1** [comment]
Ok so after a ton of investigation it seems like this phantom message issue (what I'm dubbing it) happens on both ends for a node, sometimes it occurs when you send a message to a node and it actually get sent but never shows up in message history.

**Comment by iceHtwoO** [comment]
Is there any fix for this issue?

**Comment by tmulle** [comment]
Any fix? I still see this using both Lora and MQTT.
I am told I have new direct messages according to the count but when I click on the Direct message link I don't see the new messages. This is happening on both iOS and MacOS Meshtastic applications.

Clicking on Direct Messages doesn't do anything and I can't read my messages sent to me.

<img width="396" height="312" alt="Image" src="https://github.com/user-attachments/assets/b88d7edf-1aae-4456-a33d-009f329803d2" />

<img width="258" height="491" alt="Image" src="https://github.com/user-attachments/assets/b1c8f85b-358d-4498-8484-9db5b25a1d4c" />

**Comment by cvandesande** [comment]
Any reason why this was closed? It’s still an issue?
